Adiciona validação de nome de usuário, email e nome de time
pontopython/api-bd1 pull request #2
Opened 2022-09-10 21:55 UTC by larissa-fernanda

Tipos de validações: 

Nome de usuário e nome de time:

1. - deve conter mais de 2 caracteres
2.  não pode começar com número
3. - não pode conter caracteres especiais, exceto underline "_"

email:

valida o email usando regex

2022-09-11 21:36 UTC, jnydutra requested changes

2022-09-11 21:36 UTC, jnydutra commented on validation.py
> +def validate_username():
o que acha de chamar esse método de `prompt_for_valid_username()` ou algo assim?

2022-09-11 21:36 UTC, jnydutra commented on validation.py
> +def validate_email():
Mesma coisa aqui. Que tal `prompt_for_valid_email()`?

2022-09-11 21:36 UTC, jnydutra commented on validation.py
> +def validate_team_name():
`prompt_for_valid_team_name`

2022-09-11 21:36 UTC, jnydutra commented on validation.py
> +def is_name_valid(name):
Posso propor um desafio aqui? Consegue deixar a exibição das mensagens de erro condicionadas a um parâmetro? Chamando o método com `is_name_valid(name)` só retorna se é válido ou não e chamando com `is_name_valid(name, print_errors=True)` faz a mesma coisa mas também imprime os erros.

2022-09-13 16:44 UTC, jnydutra approved these changes
Show de bola!

2022-09-13 18:44 UTC, NicSouza approved these changes

2022-09-14 04:01 UTC, Alemoreira-00 approved these changes

2022-09-14 18:03 UTC, merged