Funções para geração de lista de usuários e display em console
pontopython/api-bd1 pull request #4
Opened 2022-09-12 19:00 UTC by aleclr

Cria a lista de dicionários para os usuários do USERS.TXT, e escreve no console.

USERS.TXT utilizado como sample para os testes.

2022-09-12 23:44 UTC, jnydutra requested changes

2022-09-12 23:44 UTC, jnydutra commented on data/users.txt
> +1;Pedro;pedro@gmail.com;abc123
Bora adicionar a pasta `data` no .gitignore como mostrei aqui https://github.com/pontopython/api-bd1/pull/1/files#r969016017

2022-09-12 23:44 UTC, jnydutra commented on generate_users_list.py
> +    return display_users_list(users_list)                           # retorna e aciona o display da lista no console
Vamos separar a exibição dos dados e a parte de gerar eles. Aqui você pode apenas retornar `users_list`.

2022-09-12 23:44 UTC, jnydutra commented on generate_users_list.py
> +def display_users_list(users_list):                                 # ESCREVE A LISTA DE USUÁRIOS NO CONSOLEx
Como esse método é especifico para mostrar a lista de usuários e não uma lista qualquer você pode remover o parâmetro e carregar a lista dentro do método com `users_list = generate_users_list()`

2022-09-12 23:44 UTC, jnydutra commented on generate_users_list.py
> +def display_users_list(users_list):                                 # ESCREVE A LISTA DE USUÁRIOS NO CONSOLEx
Como esse método é especifico para mostrar a lista de usuários e não uma lista qualquer você pode remover o parâmetro e carregar a lista dentro do método com `users_list = generate_users_list()`

2022-09-12 23:44 UTC, jnydutra commented on generate_users_list.py
> +def display_users_list(users_list):                                 # ESCREVE A LISTA DE USUÁRIOS NO CONSOLEx
Como esse método é especifico para mostrar a lista de usuários e não uma lista qualquer você pode remover o parâmetro e carregar a lista dentro do método com `users_list = generate_users_list()`

2022-09-12 23:49 UTC, jnydutra commented on data/users.txt
> +1;Pedro;pedro@gmail.com;abc123
Foi mal @aleclr agora que vi o comentário. Mesmo assim acho válido colocar no `.gitignore` essa pasta e para sample data a gente cria um método `generate_users_sample_data()` que retorna uma lista de usuários testes e depois você pode criar um outro método que salva uma lista inteira de usuários novos. Fica de desafio!

2022-09-12 23:50 UTC, jnydutra commented on data/users.txt
> +1;Pedro;pedro@gmail.com;abc123
Foi mal @aleclr agora que vi o comentário. Mesmo assim acho válido colocar no `.gitignore` essa pasta e para sample data a gente cria um método `generate_users_sample_data()` que retorna uma lista de usuários testes e depois você pode criar um outro método que salva uma lista inteira de usuários novos. Fica de desafio!

2022-09-14 04:04 UTC, Alemoreira-00 approved these changes

2022-09-14 18:53 UTC, jnydutra approved these changes

2022-09-14 18:54 UTC, merged